import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const stylesDir = path.join(root, "website", "styles");

const bundles = [
  ["home.css", "home.bundle.css"],
  ["case.css", "case.bundle.css"],
];

const importPattern = /^@import\s+url\(["']?([^"')]+)["']?\);\s*$/gm;

function stripQuery(value) {
  return value.split("?")[0];
}

function resolveCss(fileName, stack = []) {
  const filePath = path.join(stylesDir, fileName);
  const source = readFileSync(filePath, "utf8");
  const imports = [];

  const body = source.replace(importPattern, (_match, importPath) => {
    const importedFile = stripQuery(importPath);
    imports.push(importedFile);
    return "";
  });

  const resolvedImports = imports
    .map((importedFile) => {
      if (stack.includes(importedFile)) {
        throw new Error(`Circular CSS import: ${[...stack, importedFile].join(" -> ")}`);
      }

      return resolveCss(importedFile, [...stack, fileName]);
    })
    .join("\n");

  return `${resolvedImports}\n/* ${fileName} */\n${body.trim()}\n`;
}

for (const [entry, output] of bundles) {
  const bundled = `/* Generated by tools/build-css.mjs. Edit source CSS modules instead. */\n${resolveCss(entry).trim()}\n`;
  writeFileSync(path.join(stylesDir, output), bundled);
}

console.log(`Generated ${bundles.length} CSS bundles.`);
